variables:
  server-port: 8080

  db-url: jdbc:postgresql://localhost:5432/bank_db
  db-username: postgres
  db-password: nasa

server:
  port: ${variables.server-port}

spring:
  application:
    name: bank-rest

  datasource:
    url: ${variables.db-url}
    username: ${variables.db-username}
    password: ${variables.db-password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml

  main:
    banner-mode: off

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
